// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-study-contexts.ts
import { createClient } from "npm:@supabase/supabase-js@^2.91.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^4.4.3";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_study_contexts_default = defineTool({
  name: "list_study_contexts",
  title: "List study contexts",
  description: "List the signed-in user's study contexts (uploaded PDFs, photos, web-search topics) with their processing status.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(20).describe("Maximum number of contexts to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb(ctx).from("study_contexts").select("id, file_name, processing_status, generation_status, created_at").order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { contexts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-study-context.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.91.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^4.4.3";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_study_context_default = defineTool2({
  name: "get_study_context",
  title: "Get study context",
  description: "Return the extracted text content of a single study context owned by the signed-in user.",
  inputSchema: {
    id: z2.string().uuid().describe("Study context id."),
    maxChars: z2.number().int().min(500).max(2e5).default(2e4).describe("Truncate the returned content to this many characters.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, maxChars }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb2(ctx).from("study_contexts").select("id, file_name, content, processing_status").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Not found" }], isError: true };
    const content = (data.content ?? "").slice(0, maxChars);
    return {
      content: [{ type: "text", text: content }],
      structuredContent: { id: data.id, file_name: data.file_name, processing_status: data.processing_status, content, truncated: (data.content ?? "").length > maxChars }
    };
  }
});

// src/lib/mcp/tools/list-lessons.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.91.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^4.4.3";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_lessons_default = defineTool3({
  name: "list_lessons",
  title: "List mini-lessons",
  description: "List mini-lessons for a study context owned by the signed-in user.",
  inputSchema: {
    contextId: z3.string().uuid().describe("Study context id whose lessons to list.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ contextId }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb3(ctx).from("mini_lessons").select("id, title, concept, lesson_order, page_start, page_end").eq("context_id", contextId).order("lesson_order", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { lessons: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-lesson.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.91.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z4 } from "npm:zod@^4.4.3";
function sb4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_lesson_default = defineTool4({
  name: "get_lesson",
  title: "Get mini-lesson",
  description: "Return the full content of a mini-lesson (title, concept, explanation, example) owned by the signed-in user.",
  inputSchema: {
    id: z4.string().uuid().describe("Mini-lesson id.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb4(ctx).from("mini_lessons").select("id, title, concept, explanation, example, lesson_order, page_start, page_end, context_id").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { lesson: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "xtcifacgiyekudoispdk";
var mcp_default = defineMcp({
  name: "erga-mcp",
  title: "Erga Study MCP",
  version: "0.1.0",
  instructions: "Tools for the Erga study app. Use `list_study_contexts` to see the user's uploaded study materials, `get_study_context` to read the extracted text of one, `list_lessons` to enumerate mini-lessons for a context, and `get_lesson` to read a single mini-lesson in full.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_study_contexts_default, get_study_context_default, list_lessons_default, get_lesson_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
